### ISSUE TITLE
GitHub Issues as work tracker and project source of truth 

### ISSUE THREAD

**Issue by PaulTreanor** [PaulTreanor/MapGuesser#1]
Just interested in experimenting with a light weight way to track issues and stuff. [Inspired by Simon Willison's coping strategies for a serial project hoarder](https://simonwillison.net/2022/Nov/26/productivity/).

## 1. Issue title's start with task type and brief description

[BUG] User login fails on Safari
[FEAT] Stop MapBox reloads on round change 
[REFACTOR] Make map components more testable 
[DOCS] Update API endpoints
[TEST] Add RTL component tests 

## 2. Break each task into subtasks if possible 

- [ ] Just a simple 
- [ ] List of markdown checkboxes 
- [ ] Because breaking tasks down 
- [ ] Helps people work faster

## 3. Update issue's status label as you make progress

1. Backlog (grey)
2. Ready for work (yellow)
3. In-progress (blue)
4. Blocked (red)
5. Review (green)
6. ...Close the Issue when PR passed

## 4. Name your branches after the issue 

`bug-123-fix-safari-login`

## 5.  Minor details
- Document anything useful to the work/branch/task/ticket in a comment in the GitHub Issues thread. Don't worry if it's messy, if it might be useful in the future consider throwing it in there.
