### ISSUE TITLE
[Feature] - Create API for locations 

### ISSUE THREAD

**Issue by PaulTreanor** [PaulTreanor/MapGuesser#2]
Currently the locations are just pulled from a [json file on the frontend](https://github.com/PaulTreanor/MapGuesser/blob/26dd2beacb51895b11a3ff2afbc7da2a5bb5593c/frontend-service/src/data/rounds.json). This JSON has 100 total locations right now (cities in Europe) but it's somewhat limiting. 

- There's only 100 locations (the biggest 100 cities in Europe) - this feels samey after a few rounds
- There's no logic ensuring the same city doesn't appear in 2 rounds in one game.(https://www.laphamsquarterly.org/luck/miscellany/making-it-less-random)
- Cheating is slightly easier because source code json
- This is limiting for adding future multiplayer functionality (which is the end goal).

## New locations 
I'd like there to be more locations, mostly cities in Europe but with a few other like mountain peaks, famous attractions (e.g. Eiffel tower), religious sites...that's all I can really think of but I'm sure there's more. I think there needs to be more like 500 locations for the game to not feel samey but it's important that the locations don't seem stupidly hard to get (4th biggest city in Slovenia or something). I want to stick to Europe for now. 

## Endpoint name 
Not totally obvious what this should be named? 

`/generated-round-locations`? 

## Tasks 
- [x] This relies on #3 
- [x] Curate a bunch of extra rounds with ChatGPT (make sure to avoid bad entries that could discourage players). 
- [x] Research best way to store rounds - probably SQLite or JSON
- [ ] Create an endpoint to get 5 random locations for the start of a game. It should return json that works easily with current frontend logic. 
- [x] Make sure a round never has the same location twice 
- [ ] Edit `game.tsx` to use this API - create a utils method in a utils file to do the actual request 
- [ ] Write some tests for the backend and frontend

**Comment by PaulTreanor** [comment]
@eoinmtreacy I wanted to discuss how we might separate the data from the code for this particular issue. I think if we're going with SQLite then it's good to have the schema and data scripts in git but store the actual data elsewhere (somewhere easier to update, not in the repo, and accessible via API to our backend service. 

I like the idea of keeping the data somewhere where we can easily update it without requiring any changes to the repo. One idea is using Google Sheets as a source of truth. It can be locked down with permissions, there's decent APIs around it, but it would only actually be called when we're building the DB. I have used Google Sheets for this before so I have some code we can reuse. 

Another option might be create a separate repo and just update store the data as a JSON or CSV file. We could literally just use this repo as our data store as GitHub also has very good APIs. I think I prefer this idea to Google Sheets. 

The concern with this approach is that we have to rebuild the DB with new data every time we deploy the backend which will make deployments a bit more complicated with more stuff to go wrong and more downtime. I think the fix for this is to just not trigger a redeploy of the DB on backend code changes - keep the DB related files in a separate directory (database-service?) 

I'm interested in hearing your thoughts on this because I haven't really looked into this and neither of these solutions feels perfect. This problem definitely needs some thought and research though.

**Comment by eoinmtreacy** [comment]
I don't know enough about Google Sheets or GitHub to persist the data, that's entirely at your discretion.

The DB building can be done in a very similar way to the way I proposed we handle CD for the `backend service`
- A/B containers
- run the "migrations"
- run the integrity tests
- stop the old DB

Although this does come very close to having a "real" database, which I'm happy enough with. I thought what we were looking for in the first place was a glorified text file.

**Comment by PaulTreanor** [comment]
I like the glorified text file a lot but I just don't think data should stored in version control past the initial demo we have right now. If you don't mind then I think a separate GitHub repo that just holds a json file for locations would be best.

 That migration workflow sounds good I'm sorry for introducing this extra complexity here.

I think JSON is the best format for this because better types than CSV, isn't as fragile with formatting as CSV files are, and it's a bit more robust around handling "," which might be in a random place name down the line.
